version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/build"
      - "/restore"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
